baseurl = "https://nyrrd.xyz"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"
[pagination]
pagerSize = 20
[services]
[services.disqus]
shortname = "nyrrd"
[markup.highlight]
style = "github-dark"
[params]
    author = "nyrrd"
#    info = "System Engineer"
    description = "nyrrd"
    keywords = "blog,developer,personal"
    avatarurl = "/img/comedian-badge-white.jpg"
    favicon_32 = "/img/favicon.ico"
    favicon_16 = "/img/favicon.ico"
    since = 2020
    enableTwemoji = true
    colorScheme = "dark"
    hidecolorschemetoggle = false
[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"
# Social links
# GITHUB
[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/nyrrd"
[caches]
  [caches.images]
    dir = ':cacheDir/images'
# GITLAB
[[params.social]]
name = "Gitlab"
icon = "fa-brands fa-gitlab fa-2x"
weight = 2
url = "https://gitlab.com/nyrrd/"
# MASTODON
[[params.social]]
name = "Mastodon"
icon = "fa-brands fa-mastodon fa-2x"
weight = 3
url = "https://mastodon.social/@nyrrd"
[params.umami]
    siteID = "0fbff15d-3277-4106-bbfe-7a436859738f"
    scriptURL = "https://cloud.umami.is/script.js" 
